name: mi_card
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
    - images/ayush.jpeg




  fonts:
    - family: Shadows
      fonts:
        - asset: fonts/ShadowsIntoLight-Regular.ttf

    - family: Yanone
      fonts:
        - asset: fonts/YanoneKaffeesatz-Light.ttf

    - family: Prompt
      fonts:
        - asset: fonts/Prompt-ExtraBold.ttf


